### ISSUE TITLE
Segmentation fault when executing rosrun speech_recog_uc_basic speech_recog_uc_basic_node en-EN

### ISSUE THREAD

**Issue by ximenad** [jopedroliveira/speech_recog_uc#1]
[ INFO] [1528125817.918205348]: Initializing Speech Recognition node
[ INFO] [1528125817.928462833]: ---------------------------------
[ INFO] [1528125817.930831183]: Defined language: en-EN
[ INFO] [1528125817.930982037]: Recognition output mode ON
[ INFO] [1528125817.931077456]: --------------------------------

[ INFO] [1528125817.931222266]: Initializing Voice Activity Detection Engine
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'AC97 2ch->4ch Copy Switch',0,0,0): No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'AC97 2ch->4ch Copy Switch',0,0,0): No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (PCM,'IEC958 Playback PCM Stream',0,0,0): No such file or directory
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (PCM,'IEC958 Playback PCM Stream',0,0,0): No such file or directory
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (PCM,'IEC958 Playback PCM Stream',0,0,0): No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
[ INFO] [1528125818.482739722]: Portaudio Initialized
[ INFO] [1528125818.483329974]: Voice Activity Detection Engine Initialized
[ INFO] [1528125821.472270406]: isSOS ------------------ New recognition started.
[ INFO] [1528125821.472455448]: New file created: /home/ximena/speech/recordings/recognition_audio_1528125821472.wav

Permission denied
Segmentation fault (core dumped)

**I don´t understand why it is dumped since I have followed all the steps. Could this problem be due to the credentials? How can I check that my credentials are okay?**

**Comment by jopedroliveira** [comment]
Hello @ximenad !
Thanks for trying this package.

As far as I can see, the setup and building ran flawlessly... The error you are getting might be due to the license.
Please, check if you have the credentials file in the proper place and if you have it correctly configured in your bashrc. Also, check if the credentials are enabled on your google cloud account.

Bests,
Pedro.

**Comment by ximenad** [comment]
What do you mean with having the credentials file in the proper place? Do we need to place it in a specific folder?
How do we enable the credentials? I have enabled the Cloud Speech API but I don't know how to do it for the credentials.

**Comment by jopedroliveira** [comment]
@ximenad please follow the instructions here: http://wiki.ros.org/speech_recog_uc#Setup

**Comment by ximenad** [comment]
I had followed these instructions. The only thing that is different is Service Account Actor role which is not available now. However, choosing Service Account User and Service Account Token Creator provides the same permissions, as I read [here](https://cloud.google.com/iam/docs/service-accounts).

**Comment by jopedroliveira** [comment]
@ximenad have you enabled billing?
Can you paste here your speech folder tree?
Can you paste here your bashrc?

The issue you are experiencing is due to the license, so let's make sure it is in the correct place! ;)

**Comment by ximenad** [comment]
I could finally fix it. The problem was that I didn't have credential .json in the speech folder. I realized yesterday when I start looking the code and the speech folder was locked, so I had to change the permissions in order to paste the credentials.

However, I paste the speech folder tree and bashrc.

My speech folder tree now is:
- ar_file
- googleapis
- grpc
- Prueba-9735a09dbec9.json
- recordings

My .bashrc file is:
_________________________________________________________________________________________________________
`#~/.bashrc: executed by bash(1) for non-login shells.
#see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
#for examples

#If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

#don't put duplicate lines or lines starting with space in the history.
#See bash(1) for more options
HISTCONTROL=ignoreboth

#append to the history file, don't overwrite it
shopt -s histappend

#for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

#check the window size after each command and, if necessary,
#update the values of LINES and COLUMNS.
shopt -s checkwinsize

#If set, the pattern "**" used in a pathname expansion context will
#match all files and zero or more directories and subdirectories.
#shopt -s globstar

#make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

#set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

#set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

#uncomment for a colored prompt, if the terminal has the capability; turned
#off by default to not distract the user: the focus in a terminal window
#should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	#We have color support; assume it's compliant with Ecma-48
	#(ISO/IEC-6429). (Lack of such support is extremely rare, and such
	#a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

#If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

#enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

#some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

#Add an "alert" alias for long running commands.  Use like so:
#sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

#Alias definitions.
#You may want to put all your additions into a separate file like
#~/.bash_aliases, instead of adding them here directly.
#See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

#enable programmable completion features (you don't need to enable
#this, if it's already enabled in /etc/bash.bashrc and /etc/profile
#sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

#ROS environment variables
source /opt/ros/indigo/setup.bash
source /home/ximena/catkin_ws/devel/setup.bash
export ROS_WORKSPACE=/home/ximena/catkin_ws
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$ROS_WORKSPACE
export ROSCONSOLOE_FORMAT='[${severity}] [${time}]: ${message}'

#Multiple machine environment
#export ROS_MASTER_URI=http://10.0.0.6:11311
#export ROS_HOSTNAME=10.0.0.52

#Google credentials
export GOOGLE_APPLICATION_CREDENTIALS=/home/ximena/speech/Prueba-9735a09dbec9.json;`
_______________________________________________________________________________________________________________


Now, I am having this issue:
[ INFO] [1528276083.118427228]: Portaudio Initialized
[ INFO] [1528276083.118508554]: Voice Activity Detection Engine Initialized
[ INFO] [1528276085.366526368]: isSOS ------------------ New recognition started.
[ INFO] [1528276085.366797421]: New file created: /home/ximena/speech/recordings/recognition_audio_1528276085366.wav

[libprotobuf FATAL /usr/local/include/google/protobuf/repeated_field.h:1522] CHECK failed: (index) < (current_size_): 
[ WARN] [1528276085.655994128]: Some error occured with the transcription, please retry
[ INFO] [1528276086.874281478]: isEOS ------------------ Recognition stoped.

**Comment by jopedroliveira** [comment]
@ximenad that error is related to the transcription itself.
What I recommend you do is to verify the audio file generated (you can find it in /home/ximena/speech/recordings/recognition_audio_1528276085366.wav).
If everything is ok with your audio file, then make sure you have declared the correct transcription language ([check instructions here](http://wiki.ros.org/speech_recog_uc#Customize_parameters)

If there is a problem with your audio file, make sure the defined sample_rate is in the microphone sample_rate range. Also, verify if you have defined the correct microphone name.

**Comment by ximenad** [comment]
Okay. Thank you very much.
I will do that and let you know when it works.

**Comment by ximenad** [comment]
I am having problems when running in English, but in Spanish it works perfectly.
The error when I run "rosrun speech_recog_uc_basic speech_recog_uc_basic_node en-EN" is:
________________________________________________________________________________________________________
[ INFO] [1528276083.118427228]: Portaudio Initialized
[ INFO] [1528276083.118508554]: Voice Activity Detection Engine Initialized
[ INFO] [1528276085.366526368]: isSOS ------------------ New recognition started.
[ INFO] [1528276085.366797421]: New file created: /home/ximena/speech/recordings/recognition_audio_1528276085366.wav

[libprotobuf FATAL /usr/local/include/google/protobuf/repeated_field.h:1522] CHECK failed: (index) < (current_size_):
[ WARN] [1528276085.655994128]: Some error occured with the transcription, please retry
[ INFO] [1528276086.874281478]: isEOS ------------------ Recognition stoped.
________________________________________________________________________________________________________
I am checking the audio file in English and it is okay. I didn't change any parameters since I am using the same microphone as yours.

**Comment by jopedroliveira** [comment]
Hello @ximenad 
According to the logs you are posting, everything is ok with the node.
The problem seems to be with the google response.
Please check if the credentials you generated are enabled, the billing profile is set up, and everything is ok on google console.

**Comment by ximenad** [comment]
Hello @jopedroliveira 
I don´t think is a problem of the credentials because I run:
rosrun speech_recog_uc_basic speech_recog_uc_basic_node es-ES
or
rosrun speech_recog_uc_basic speech_recog_uc_basic_node pt-PT

and it works perfectly. Even in Spanish, it understands some english words.

**Comment by jopedroliveira** [comment]
@ximenad in that case, try to run 
```rosrun speech_recog_uc_basic speech_recog_uc_basic_node```
without the language code. by default, it will use en

**Comment by jopedroliveira** [comment]
For english, the language code is **en-EN**

**Comment by ximenad** [comment]
I have found my problem... it was my english accent, american. If I use language as en-US, instead of en-EN, it works perfectly.
I really appreciate all your help. Thank you very much. I will like to use your code for my master thesis, can I?. If so, do you have any paper I can use as reference? or do I cite the ROS wiki and github webpages?

**Comment by jopedroliveira** [comment]
@ximenad 
I'm glad to help! Feel free to try the direction of arrival feature as well!
Regarding citation, you should cite the associated paper. However, it is still pending approval.
I will keep the ROS WIKI updated so you can check if the paper is published on your timeline.
In any case, you should cite the ROS wiki and repo as well. I will add the package on ROS package list soon. 
Let me know if you need more support!
Good work ;)
